### ISSUE TITLE
Tambah field status di table promotion

### ISSUE THREAD

**Issue by indrysfa** [indrysfa/travel-go#7]
ka tambah field field status ya buat di table promotion, karna nanti mau dibuat sistem aktif / non aktif, type = integer
![image](https://user-images.githubusercontent.com/61085159/111021174-21163480-83fd-11eb-94c9-1a402f891fd5.png)

& backendnya ika belom buat ?
@Mahananiika

**Comment by rysxa** [comment]
project done
